[package]
name = "tpool"
description = "So simple thread pool"
version = "0.1.3"
authors = ["Bells307"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bells307/tpool"

[dependencies]
scopeguard = "1.2.0"
parking_lot = "0.12.3"
